In [1]:
from sqlalchemy import create_engine
import xlrd
import pandas as pd
import numpy as np
import datacompy 
from termcolor import colored
import colorama
from colorama import Fore,Back,Style 
# colorama.init(autoreset=True)
# from pandas_profiling import profileReport

In [2]:
# pip install datacompy

In [3]:
engine = create_engine('mysql+pymysql://faiz:Faiz7862@localhost/aiinhome')
print("Connected")

Connected

In [5]:
df1 = pd.read_sql_table(table_name="ap_basic_data",con=engine)
df1

,id,MATNR,SPRAS,MAKTX,MBRSH,MTART,GROUP,XCHPF,SERLV,MSTAE,...,MHDRZ,MHDHB,MHDLP,RDMHD,IPRKZ,SLED_BBD,RBNRM,QMPUR,HUTYP,PSTAT
0,1,10041,EN,SPIN FINISH SPEC 130.F.007 PNT 93-80%,C,ROH,KVELDFQBGC,None,None,None,...,None,None,None,None,None,None,None,X,None,KVELDFQBGC
1,2,10042,EN,SPIN FINISH LUROL TC-12683 PNT-96-80%,C,ROH,KVELDFQBGC,None,None,None,...,None,None,None,None,None,None,None,X,None,KVELDFQBGC
2,3,10044,EN,SPIN FINISH TC-15531 PNT 96-45%,C,ROH,KVELDFQBGC,None,None,None,...,None,None,None,None,None,None,None,X,None,KVELDFQBGC
3,4,10045,EN,SPIN FINISH PNT 93-45%,C,ROH,KVELDFQBGC,None,None,None,...,None,None,None,None,None,None,None,X,None,KVELDFQBGC
4,5,10046,EN,SPIN FINISH TRET 107,C,ROH,KVELDFQBGC,None,None,None,...,None,None,None,None,None,None,None,X,None,KVELDFQBGC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2272,2273,0,EN,MISC ENVIRONMENTAL EXPENSE,C,NLAG,KVELFBC,None,None,None,...,None,None,None,None,None,None,None,None,None,KVELFBC
2273,2274,0,EN,MISC LAB/QUALITY SUPPLIES,C,NLAG,KVELFBC,None,None,None,...,None,None,None,None,None,None,None,None,None,KVELFBC
2274,2275,0,EN,MISC OFFICE SUPPLIES,C,NLAG,KVELFBC,None,None,None,...,None,None,None,None,None,None,None,None,None,KVELFBC
2275,2276,0,EN,MISC PROJECT ITEMS,C,NLAG,KVELFBC,None,None,None,...,None,None,None,None,None,None,None,None,None,KVELFBC
2276,2277,0,EN,MISC SAFETY SUPPLIES,C,NLAG,KVELFBC,None,None,None,...,None,None,None,None,None,None,None,None,None,KVELFBC

In [6]:
df2 = pd.read_sql_table(table_name="ap_plant_data",con=engine)
df2

,id,MATNR,WERKS,GROUP,AUSME,XCHPF,SERNP,MMSTA,MMSTD,MTVFP,...,NCOST,AWSLS,LOSGR,PPSKZ,RRP_TYPE,WHERE_BOM_FLG,GR_PROC_TIME,GI_PROC_TIME,ZC_CONVH,PSTAT
0,1,10041,N170,KVELDFQBGC,LBS,None,None,None,2021-01-01,01,...,None,2,None,None,None,None,None,None,None,KVELDFQBGC
1,2,10042,N170,KVELDFQBGC,LBS,None,None,None,2021-01-01,01,...,None,2,None,None,None,None,None,None,None,KVELDFQBGC
2,3,10044,N170,KVELDFQBGC,LBS,None,None,None,2021-01-01,01,...,None,2,None,None,None,None,None,None,None,KVELDFQBGC
3,4,10045,N170,KVELDFQBGC,LBS,None,None,None,2021-01-01,01,...,None,2,None,None,None,None,None,None,None,KVELDFQBGC
4,5,10046,N170,KVELDFQBGC,LBS,None,None,None,2021-01-01,01,...,None,2,None,None,None,None,None,None,None,KVELDFQBGC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2277,2278,0,N170,KVELFBC,EA,None,None,None,2001-01-20,None,...,None,2,None,None,None,None,None,None,None,KVELFBC
2278,2279,0,N170,KVELFBC,EA,None,None,None,2001-01-20,None,...,None,2,None,None,None,None,None,None,None,KVELFBC
2279,2280,0,N170,KVELFBC,EA,None,None,None,2001-01-20,None,...,None,2,None,None,None,None,None,None,None,KVELFBC
2280,2281,0,N170,KVELFBC,EA,None,None,None,2001-01-20,None,...,None,2,None,None,None,None,None,None,None,KVELFBC
2281,2282,0,N170,KVELFBC,EA,None,None,None,2001-01-20,None,...,None,2,None,None,None,None,None,None,None,KVELFBC

In [13]:
Intdf1=[]
Vardf1=[]
Datedf1=[]
for col,dtype in df1.dtypes.iteritems():
#     print(col,dtype)
    if dtype=='int64':
        Intdf1.append(col)
    elif dtype=='object':
        Vardf1.append(col)
    elif dtype=='datetime64[ns]':
         Datedf1.append(col)
    
print(colored("*******************************************COLUMNS FROM TABLE basic_data******************************************************",'green'))        
print(colored("TYPE INT:",'red'))
print(colored(f'{Intdf1}\n','blue'))
print(colored("TYPE VARCHAR:",'red'))
print(colored(f' {Vardf1}','blue'))

Intdf2=[]
Vardf2=[]
Datedf2=[]
for col1,dtype1 in df2.dtypes.iteritems():
#     print(col,dtype)
    if dtype1=='int64':
        Intdf2.append(col1)
    elif dtype1=='object':
        Vardf2.append(col1)
    elif dtype=='datetime64[ns]':
         Datedf1.append(col)
print(colored("*****************************************COLUMNS FROM TABLE plant_data******************************************************",'green'))                    
print(colored("TYPE INT:",'red'))
print(colored(f'{Intdf2}\n','blue'))
print(colored("TYPE VARCHAR:",'red'))
print(colored(f'{Vardf2}','blue'))


def DataRelation(col,col1):
        dfcol= df1[col].dropna()
            #      print(dfcol)
        dfcol1= df2[col1].dropna()
            #      print(dfcol1
        intersec=pd.Series(np.intersect1d(dfcol, dfcol1))
            #      print(intersec)
        if not df1[col].empty and not df2[col1].empty:
            uque=dfcol.unique()
                #      print(uque)
            uque1=dfcol1.unique()
                #      print(uque1)
            
            DataMax = max(len(uque),len(uque1))
        #              print(DataMax)
            com_len=len(intersec)
                #      print(com_len)
            if DataMax !=0:
                percentage = str(int((100/DataMax)*com_len))+'%'
                #          print(percentage)
                if percentage != '0%':
                    print(colored(f'{col}: FROM DATA FRAME1 AND  {col1} FROM DATA FRAME2 MATCHED BY {percentage}','magenta'))
                    intrdf= pd.DataFrame(intersec, columns=[col])
                #              print(intrdf)
                    MrgData= len(intrdf.merge(df1[col],how='inner'))
                #              print(MrgData)
            
                    intrdf= pd.DataFrame(intersec, columns=[col1])
                #              print(intrdf)
                    MrgData1= len(intrdf.merge(df2[col1],how='inner'))
                #              print(MrgData1)
            
                    if MrgData==com_len:
                        if MrgData1==com_len:
                            print(colored('One to One','blue'))
                        else:
                            print(colored('One to Many','blue'))
                    else:
                        if MrgData1==com_len:
                            print(colored('Many to One','blue'))
                        else:
                            print(colored('Many to Many','blue')) 
                            
print(colored("*******************************************ANALYSING INTEGER TYPE COLUMN WITH PERCENTAGE AND TYPE OF JOIN********************\n",'green'))
for col in Intdf1:
    for col1 in Intdf2:
#         print(col)
#         print(col1)
        DataRelation(col,col1)
    
print(colored("********************************************ANALYSING VARCHAR TYPE COLUMN WITH PERCENTAGE AND TYPE OF JOIN*******************\n",'green'))            
for col in Vardf1:
    for col1 in Vardf2: 
#         print(col)
#         print(col1)
        DataRelation(col,col1)


print(colored("*******************************************ANALYSING DATE&TIME TYPE COLUMN WITH PERCENTAGE AND TYPE OF JOIN******************\n",'green'))            
for col in Datedf1:
#     print(col)
    for col1 in Datedf2:
#         print(col1) 
        DataRelation(col,col1)

*******************************************COLUMNS FROM TABLE basic_data******************************************************
TYPE INT:
['id', 'MATNR', 'BISMT']

TYPE VARCHAR:
 ['SPRAS', 'MAKTX', 'MBRSH', 'MTART', 'GROUP', 'XCHPF', 'SERLV', 'MSTAE', 'MATKL', 'EXTWG', 'MEINS', 'SPART', 'PRDHA', 'MTPOS_MARA', 'BRGEW', 'NTGEW', 'GEWEI', 'VOLUM', 'VOLEH', 'GROES', 'EAN11', 'NUMTP', 'LAENG', 'BREIT', 'HOEHE', 'MEABM', 'KZKFG', 'ANP', 'PROFL', 'KZUMW', 'MSTAV', 'MSTDV', 'TRAGR', 'VHIART', 'KZGVH', 'ERGEW', 'ERGEI', 'GEWTO', 'ERVOL', 'ERVOE', 'VOLTO', 'BSTME', 'VABME', 'MFRPN', 'MFRNR', 'MPROF', 'EKWSL', 'RAUBE', 'TEMPB', 'STOFF', 'WESCH', 'ETIAR', 'ETIFO', 'XGCHP', 'MHDRZ', 'MHDHB', 'MHDLP', 'RDMHD', 'IPRKZ', 'SLED_BBD', 'RBNRM', 'QMPUR', 'HUTYP', 'PSTAT']
*****************************************COLUMNS FROM TABLE plant_data******************************************************
TYPE INT:
['id', 'MATNR', 'DISPO', 'PLIFZ', 'SBDKZ', 'AWSLS']

TYPE VARCHAR:
['WERKS', 'GROUP', 'AUSME', 'XCHPF', 'SERNP', 'MMSTA', 'MTVFP', 'KZECH', 'KZKRI', 'WEBAZ', 'LGPRO', 'INSMK', 'O', 'LADGR', 'VRVEZ', 'VBEAZ', 'VBAMG', 'PRCTR', 'EKGRP', 'KAUTB', 'USEQU', 'KORDB', 'MTVER', 'HERKL', 'HERKR', 'STEUC', 'INDUS', 'DISGR', 'MAABC', 'DISMM', 'MINBE', 'FXHOR', 'LFRHY', 'DISLS', 'BSTMI', 'BSTMA', 'BSTFE', 'MABST', 'AUSSS', 'TAKZT', 'RDPRF', 'BSTRF', 'BESKZ', 'SOBSL', 'RGEKZ', 'VSPVB', 'FABKZ', 'LGFSB', 'KZKUP', 'SCHGT', 'EPRIO', 'FHORI', 'MRPPP', 'EISBE', 'EISLO', 'RWPRO', 'SHFLG', 'SHZET', 'PERKZ', 'PERIV', 'AUFTL', 'AUTRU', 'KZKFK', 'STRGR', 'VRMOD', 'VINT1', 'VINT2', 'MISKZ', 'PRGRP', 'PRWRK', 'UMREF', 'WZEIT', 'KZPSP', 'BZ', 'CA', 'CB', 'ALTSL', 'KAUSF', 'KZBED', 'AHDIS', 'KZAUS', 'AUSDT', 'NFMAT', 'SAUFT', 'SFEPR', 'FRTME', 'FEVOR', 'UEETO', 'UEETK', 'UNETO', 'BEARZ', 'RUEZT', 'TRANZ', 'DZEIT', 'BASMG', 'MAXLZ', 'LZEIH', 'XMCNG', 'QMATA', 'KZDKZ', 'PRFRQ', 'SSQSS', 'QZGTP', 'QSSYS', 'NCOST', 'LOSGR', 'PPSKZ', 'RRP_TYPE', 'WHERE_BOM_FLG', 'GR_PROC_TIME', 'GI_PROC_TIME', 'ZC_CONVH', 'PSTAT']
*******************************************ANALYSING INTEGER TYPE COLUMN WITH PERCENTAGE AND TYPE OF JOIN********************

id: FROM DATA FRAME1 AND  id FROM DATA FRAME2 MATCHED BY 99%
One to One
MATNR: FROM DATA FRAME1 AND  MATNR FROM DATA FRAME2 MATCHED BY 99%
Many to Many
BISMT: FROM DATA FRAME1 AND  MATNR FROM DATA FRAME2 MATCHED BY 99%
Many to Many
********************************************ANALYSING VARCHAR TYPE COLUMN WITH PERCENTAGE AND TYPE OF JOIN*******************

GROUP: FROM DATA FRAME1 AND  GROUP FROM DATA FRAME2 MATCHED BY 100%
Many to Many
GROUP: FROM DATA FRAME1 AND  PSTAT FROM DATA FRAME2 MATCHED BY 100%
Many to Many
XCHPF: FROM DATA FRAME1 AND  XCHPF FROM DATA FRAME2 MATCHED BY 100%
Many to Many
MEINS: FROM DATA FRAME1 AND  AUSME FROM DATA FRAME2 MATCHED BY 88%
Many to Many
HOEHE: FROM DATA FRAME1 AND  MTVER FROM DATA FRAME2 MATCHED BY 15%
Many to Many
KZUMW: FROM DATA FRAME1 AND  XCHPF FROM DATA FRAME2 MATCHED BY 100%
Many to Many
QMPUR: FROM DATA FRAME1 AND  XCHPF FROM DATA FRAME2 MATCHED BY 100%
Many to Many
PSTAT: FROM DATA FRAME1 AND  GROUP FROM DATA FRAME2 MATCHED BY 100%
Many to Many
PSTAT: FROM DATA FRAME1 AND  PSTAT FROM DATA FRAME2 MATCHED BY 100%
Many to Many
*******************************************ANALYSING DATE&TIME TYPE COLUMN WITH PERCENTAGE AND TYPE OF JOIN******************

In [15]:
print("Thank You "+"\u2764\ufe0f")

Thank You ❤️